### ISSUE TITLE
how to install gentoo on macbook

### ISSUE THREAD

**Issue by wenxingxing** [coldnew/macbookpro-2015-config#2]
hi there, i'm trying to install gentoo on my macbook, but i can't boot gentoo minimal live cd...
do you have any kind of tutorial or guide for that, thx.

**Comment by ahxxm** [comment]
any error message?

**Comment by wenxingxing** [comment]
dmesg says
`wl driver 6.30.223.271 () failed with code 1`

wifi don't work..
