### ISSUE TITLE
Have you solved the SD Card device problem?

### ISSUE THREAD

**Issue by wminyu** [coldnew/macbookpro-2015-config#6]
I have the same problem as you on the  SD Card device , Have you solved it?
Here’s my lsusb info:
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 05ac:0273 Apple, Inc. Internal Keyboard/Trackpad (ISO)
Bus 001 Device 003: ID 05ac:8290 Apple, Inc. Bluetooth Host Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
kernel version: 4.9.34
and, modprobe sdhci-pci make no difference

**Comment by coldnew** [comment]
I didn't use Gentoo on MBPR recently, I'll re-test it on this weekend :P 

As far as I know, kernel 4.9.x didn't solve this issue, so I think I'll test latest kernel for this case.

**Comment by coldnew** [comment]
The first thing I find is today I reboot my MBPR2015 from MacOSX to Linux, the lsusb give me this result:

![lsusb](https://user-images.githubusercontent.com/39703/28721860-440ea1de-73e4-11e7-843a-e5af95738eee.png)


Which means maybe the `05ac:8406` re-appear to lsusb is due to I update my MacOSX to latest version, now I think I need rebuild my kernel for this device.

**Comment by coldnew** [comment]
Actually I think I can read my sdcard if `05ac:8406` can be listed by `lsusb`, I need more test for this.

Also can try : 

```
 sudo rmmod sdhci-pci sdhci
 sudo modprobe sdhci debug_quirks2=4
 sudo modprobe sdhci-pci
```

ref: https://wiki.archlinux.org/index.php/MacBookPro10,x#Memory_Card_.28SDHCI.2FSDX.29_Reader

**Comment by coldnew** [comment]
In my kernel config: [gentoo-sources-4.8.12](https://github.com/coldnew/macbookpro-2015-config/blob/master/examples/kernel-config/gentoo-sources-4.8.12) can use sdcard slot without any error.

I didn't do anything, just upgrade my MacOSX and reboot to linux, hope this can work on every boot.

**Comment by wminyu** [comment]
yeah, after update my Mac os,  I can find my sd card now. thank you!

**Comment by coldnew** [comment]
For anyone has this issue, please upgrade to `macOS Sierra` version `10.12.6` and check if `lsusb` can find device id `05ac:8406` or not :)
